apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi  

---

apiVersion: batch/v1
kind: CronJob
metadata:
  name: backup-cronjob
spec:
  schedule: "*/1 * * * *"  
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: backup-container
            image: sometimesvictor/gdrive-backup-image:v1
            volumeMounts:
            - name: data-volume
              mountPath: data  
          volumes:
          - name: data-volume
            persistentVolumeClaim:
              claimName: data-pvc  
          restartPolicy: OnFailure
